### ISSUE TITLE
。。。

### ISSUE THREAD

**Issue by lovedabaozi** [tankery/permission-requester#1]
当用户勾选 记住操作，然后选择禁止权限的时候， 下一次 请求权限的时候，不会弹框，这个时候需要去系统界面手动打开权限，那么问题来了， 怎么监听到请求权限用户选择记住 拒绝这个操作。

**Comment by tankery** [comment]
如果用户勾选不再提醒。 系统 API shouldShowRequestPermissionRationale 会返回false。由此可知用户勾选了不再提醒。
