### ISSUE TITLE
Memory leak detected in PermissionRequestActivity (leak canary)

### ISSUE THREAD

**Issue by behelit** [tankery/permission-requester#2]
A leak was detected in PermissionRequestActivity

```
* me.tankery.permission.PermissionRequestActivity has leaked:
    * GC ROOT android.os.HandlerThread.<Java Local>
    * references android.os.Message.obj
    * references me.tankery.permission.PermissionRequestActivity$4.this$0 (anonymous implementation of android.content.DialogInterface$OnClickListener)
    * leaks me.tankery.permission.PermissionRequestActivity instance
```

![image](https://user-images.githubusercontent.com/11013784/38590458-a1983d4c-3d74-11e8-8c86-f505deb9b5f6.png)

**Comment by tankery** [comment]
Hi, @behelit 
Thanks for feedback. I'm not able to reproduce this leak you found by using leakcanary, but I do found there maybe a potainal leak point, so I done a fix for it. Maybe you can download new version of code to verify, Thanks a lot~
